parameters:

services:
    # Enregistrement automatique des repositories
    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']
        autowire: true
        autoconfigure: true

    # Enregistrement automatique des controllers
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    Gregwar\CaptchaBundle\Generator\PhraseBuilder:
        arguments: ["@session", "%gregwar_captcha.config%"]
        class: Gregwar\CaptchaBundle\Generator\PhraseBuilder\PhraseBuilder
